### PR TITLE
Update to J3.4-rc

### PR DESCRIPTION
**Pull request by nicksavov**
Reference:
https://github.com/joomla-extensions/install-from-web-server/pull/4

### CODE REVIEW

**Comment by nicksavov** [comment]
Seems like I broke something moving the repo to J3.4:

> Fatal error: JApplicationCms::getUserState(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Joomla\Registry\Registry&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in libraries/cms/application/cms.php on line 513

It might be totally unrelated to Install from Web though.

**Comment by coolbung** [comment]
Does the server really need to be updated to 3.4 ? We are of course aiming for supporting Web Installer before 3.4 comes.. but don't think we need to rush updating the web installer itself to 3.4 ?

**Comment by zero-24** [comment]
A update (using joomla core updater) works with two steps 321 --> 327 --> 336

Also the update to 34rc works but i think it should be updated if 34 stable is released.

**Comment by coolbung** [comment]
Note that we're talking about updating the apps server component that resides only on the j.org servers. I see no reason to rush that update, I feel we should instead focus on getting the web installer completed.

**Comment by zero-24** [comment]
@nicksavov you need to clean your cache and all works ok :smile: (just experienced the same issue here)

**Comment by zero-24** [comment]
BTW it looks like that the current version (on the CDN) use the last stable release 336.

**Comment by nicksavov** [comment]
@coolbung sorry, I didn't realize it was for the server. Feel free to close it.

@zero-24 good catch! I wouldn't have thought clearing cache would fix an issue like that :smile: Thanks!

**Comment by coolbung** [comment]
Do we agree that we only want the specific com_apps extension to be in this repo rather than the entire Joomla ? Will close this in that case.

@zero-24 @beat @wilsonge @nicksavov

**Comment by zero-24** [comment]
agree but i think we should wait for the switch on a new and working jed3 server ;)

**Comment by coolbung** [comment]
Without doubt :)

**Comment by beat** [comment]
:+1:

**Comment by nicksavov** [comment]
+1

**Pull request closed without merging**
